---
name: bbpress-permalinks-with-id-development
services:
  php:
    build:
      dockerfile: ./../tests/application/containers/php/php.Dockerfile
      context: ./
      target: php-base-with-composer
      args:
        UID: 1001
        GID: 1001
      provenance: false
      sbom: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    read_only: true
    init: true
    tty: true
    environment:
      GITHUB_ACTIONS: ${GITHUB_ACTIONS:-false}
    volumes:
      - ./../:/home/php/app
      - ./../tmp/composer:/home/php/.composer
    tmpfs:
      - /tmp
