---
name: bbpress-permalinks-with-id-development
services:
  php:
    build:
      dockerfile: ./containers/php/Dockerfile
      context: ./
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    read_only: true
    init: true
    tty: true
    volumes:
      - ./../:/root/project
