---
name: bbpress-permalinks-with-id-development
services:
  php:
    build:
      dockerfile: ./containers/php/Dockerfile
      context: ./
      args:
        UID: 1001
        GID: 1001
      provenance: false
      sbom: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    read_only: true
    init: true
    tty: true
    volumes:
      - ./../:/home/php/app
      - ./../tmp/composer:/home/php/.composer
    tmpfs:
      - /tmp
