version: 2
updates:
  - package-ecosystem: composer
    directories:
      - development/hooks-generator
      - development/php-stan
      - .github/phpcs
      - .github/phpmd
      - .github/psalm
      - .github/tests/application
    versioning-strategy: increase
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    assignees:
      - korobochkin

  - package-ecosystem: github-actions
    directories:
      - /
      - .github/actions/hooks-generator
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - korobochkin
