version: 2
updates:
  - package-ecosystem: composer
    directories:
      - development/hooks-generator
      - development/php-stan
      - development/phpcs
      - development/phpmd
      - development/psalm
      - tests/application
    versioning-strategy: increase
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    assignees:
      - korobochkin

  - package-ecosystem: docker
    directories:
      - ./tests/application/containers/php
      - ./tests/application/containers/syslog
      - ./tests/application/containers/wordpress
    cooldown:
      default-days: 10
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
    assignees:
      - korobochkin

  - package-ecosystem: docker-compose
    directories:
      - ./development
      - ./tests/application
    cooldown:
      default-days: 10
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
    assignees:
      - korobochkin

  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - korobochkin
