language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failures:
    - php: nightly

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
#    composer global require wp-coding-standards/wpcs
#    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs


install:
  - composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader --classmap-authoritative
  - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard


script:
  #- vendor/bin/phpcs source/ --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - vendor/bin/phpcs source/ --standard=phpcs.ruleset.xml
  - phpunit
