sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  allow_failures:
    - php: nightly

before_script:
  - bash bin/install-wp-tests.sh test root '' localhost $WP_VERSION

install:
  - wp plugin install bbpress --activate
  - composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader --classmap-authoritative

script:
  - phpunit -c phpunit.xml.dist
