<?php

declare(strict_types=1);

namespace Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\TestCases\PluginIsNotActive;

use Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\Abstracts\AbstractHttpTestCase;
use Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\DataProviders\ForumDataProvider;
use Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\Entities\Posts\Forum;
use Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\Entities\Posts\Status;
use Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\Entities\Posts\Topic;
use Korobochkin\BBPressPermalinksWithIdTestsApplication\Tests\Services\BrowserActions;
use PHPUnit\Framework\Attributes;

/**
 * @internal
 */
#[Attributes\CoversNothing]
class TopicsTest extends AbstractHttpTestCase
{
    /**
     * Here I finalize building each Post instance with Type::Topic.
     * DataProviders are invoked before any tests are ran,
     * but IDs for Type::Forum appear after actual tests execution (generated by DB).
     * That is why it can not be done in the DataProvider itself.
     * As an alternative it can be done in test*-methods,
     * but I would like to keep test*-methods small, clean and simple.
     */
    protected function assertPreConditions(): void
    {
        parent::assertPreConditions();

        foreach (ForumDataProvider::getTopics() as [$forum, $topic]) {
            /*
             * @var Forum $forum
             * @var Topic $topic
             */
            $topic->setParentForumId($forum->getId());
        }
    }

    #[Attributes\DependsOnClass(ForumsTest::class)]
    #[Attributes\DataProviderExternal(ForumDataProvider::class, 'getTopics')]
    public function testCreateTopic(Forum $forum, Topic $topic): void
    {
        $this->browsers->admin->followRedirects(true);
        BrowserActions::createPostViaWPAdmin($this->browsers->admin, $topic);
        $this->assertPageStatusIs200($this->browsers->admin->getResponse());

        $this->assertIsInt($topic->getId());
        $this->assertSame(Status::Publish, $topic->getStatus());
    }
}
