name: CI Debug

on: workflow_dispatch

concurrency:
  group: 'ci-debug'
  cancel-in-progress: true

permissions: {}

jobs:
  tests-application:
    name: Run Application Tests
    uses: ./.github/workflows/tests-application.yml
    permissions:
      contents: read
    strategy:
      matrix:
        config:
          - wordpress_arg_base_image: 'wordpress:latest'
            cli_arg_base_image: 'wordpress:cli'
            wordpress_arg_plugin_bbpress_zip_url: 'https://downloads.wordpress.org/plugin/bbpress.2.6.14.zip'
            wordpress_arg_theme_zip_url: 'https://downloads.wordpress.org/theme/twentytwelve.4.6.zip'
          - wordpress_arg_base_image: 'wordpress:6.0.0'
            cli_arg_base_image: 'wordpress:cli'
            wordpress_arg_plugin_bbpress_zip_url: 'https://downloads.wordpress.org/plugin/bbpress.2.6.14.zip'
            wordpress_arg_theme_zip_url: 'https://downloads.wordpress.org/theme/twentytwelve.4.6.zip'
          - wordpress_arg_base_image: 'wordpress:4.1.2' # Latest available Docker image despite WordPress has more 4.1.X releases.
            cli_arg_base_image: 'wordpress:cli'
            wordpress_arg_plugin_bbpress_zip_url: 'https://downloads.wordpress.org/plugin/bbpress.2.5.14.zip'
            wordpress_arg_theme_zip_url: 'https://downloads.wordpress.org/theme/twentytwelve.4.6.zip'
    secrets:
      MYSQL_DATABASE: ${{ secrets.APPLICATION_TESTS_MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.APPLICATION_TESTS_MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.APPLICATION_TESTS_MYSQL_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.APPLICATION_TESTS_MYSQL_ROOT_PASSWORD }}
      WORDPRESS_ADMIN_LOGIN: ${{ secrets.APPLICATION_TESTS_WORDPRESS_ADMIN_LOGIN }}
      WORDPRESS_ADMIN_PASSWORD: ${{ secrets.APPLICATION_TESTS_WORDPRESS_ADMIN_PASSWORD }}
      WORDPRESS_ADMIN_EMAIL: ${{ secrets.APPLICATION_TESTS_WORDPRESS_ADMIN_EMAIL }}
    with:
      WORDPRESS_ARG_BASE_IMAGE: ${{ matrix.config.wordpress_arg_base_image }}
      WORDPRESS_ARG_PLUGIN_BBPRESS_ZIP_URL: ${{ matrix.config.wordpress_arg_plugin_bbpress_zip_url }}
      WORDPRESS_ARG_THEME_ZIP_URL: ${{ matrix.config.wordpress_arg_theme_zip_url }}
      CLI_ARG_BASE_IMAGE: ${{ matrix.config.cli_arg_base_image }}
      WORDPRESS_DOMAIN: 'one.wordpress.test'
      WORDPRESS_SITE_TITLE: 'Test Site'
      WORDPRESS_SITE_LOCALE: 'en_US'

#  ci-debug:
#    name: 'Debug environment variables'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Debug GITHUB_ Variables
#        run: env | grep GITHUB_
#
#      - name: Dump github Variable
#        run: echo '${{ toJson(github) }}'
#
#      - name: Dump runner Variable
#        run: echo '${{ toJson(runner) }}'
