name: CI Debug

on: workflow_dispatch

concurrency:
  group: 'ci-debug'
  cancel-in-progress: true

permissions: {}

jobs:
  ci-debug:
    name: 'Debug environment variables'
    runs-on: ubuntu-latest
    steps:
      - name: Debug GITHUB_ Variables
        run: env | grep GITHUB_

      - name: Dump github Variable
        run: echo '${{ toJson(github) }}'

      - name: Dump runner Variable
        run: echo '${{ toJson(runner) }}'

  run-workflow:
    name: 'Run another Workflow'
    needs: ci-debug
    uses: ./.github/workflows/release.yml
    permissions:
      contents: read

#  after-run-workflow:
#    name: 'Check environment'
#    needs: run-workflow
#    environment: 'WordPress.org Production'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Slug
#        run: echo '${{ vars.SLUG }}'
