name: CI Debug

on: workflow_dispatch

concurrency:
  group: 'ci-debug'
  cancel-in-progress: true

permissions: {}

jobs:
  tests-application:
    name: Run Application Tests
    uses: ./.github/workflows/tests-application.yml
    permissions:
      contents: read

#  ci-debug:
#    name: 'Debug environment variables'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Debug GITHUB_ Variables
#        run: env | grep GITHUB_
#
#      - name: Dump github Variable
#        run: echo '${{ toJson(github) }}'
#
#      - name: Dump runner Variable
#        run: echo '${{ toJson(runner) }}'
