name: Deploy to WordPress.org

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      SVN_USERNAME:
        required: true
      SVN_PASSWORD:
        required: true

concurrency:
  group: deploy
  cancel-in-progress: false

permissions: {}

jobs:
  deploy:
    name: 'Deploy to WordPress.org. Tag: ${{ inputs.version }}'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: 'WordPress.org'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ vars.SLUG }}
          VERSION: ${{ inputs.version }}
          INPUT_DRY_RUN: ${{ vars.INPUT_DRY_RUN }}
          INPUT_GENERATE_ZIP: ${{ vars.INPUT_GENERATE_ZIP }}
