name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
  workflow_call:

concurrency:
  group: release
  cancel-in-progress: false

permissions: {}

jobs:
  tests:
    name: 'Tests'
    uses: ./.github/workflows/tests.yml
    if: ${{ !github.event.release.prerelease }}
    permissions:
      contents: read

  plugin-check:
    name: 'Plugin Check'
    uses: ./.github/workflows/plugin-check.yml
    if: ${{ !github.event.release.prerelease }}
    permissions:
      contents: read
