name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

permissions: {}

jobs:
  check-prerelease:
    name: 'Check prerelease'
    runs-on: ubuntu-latest
    permissions: {}
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: 'It it a prerelease'
        run: 'echo "It is a prerelease. The jobs should not be executed."'

  tests:
    name: 'Tests'
    needs: check-prerelease
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
