name: Application Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  application-tests:
    name: Application Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        cleanup: true

    - name: Docker Compose Up --help
      working-directory: .github/tests/application
      run: docker compose up --help

    - name: Docker Compose Up
      working-directory: .github/tests/application
      run: make up

    - name: Composer Install
      working-directory: .github/tests/application
      run: make composer_install_from_host

    - name: Run Application Tests
      working-directory: .github/tests/application
      run: make run_tests_from_host

    - name: Docker Compose Down
      working-directory: .github/tests/application
      if: always()
      run: make down
