name: Code Testing

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'feature/**'

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

jobs:
  php-syntax-check:
    name: 'PHP ${{ matrix.php-versions }} Syntax Check'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '5.6'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: none
          tools: none
          ini-file: development
          php-version: ${{ matrix.php-versions }}

      - name: Run PHP Syntax Check
        run: 'find . -type f -name "*.php" -not -path "./.github/*" -print0 | xargs --null --verbose --max-procs=4 --max-args=1 php --syntax-check'

  phpcs:
    name: 'PHP Coding Standards and Compatibility'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          ini-file: development
          extensions: filter, libxml, tokenizer, xmlreader, iconv, mbstring
          tools: composer

      - name: Detect Composer Cache Directory
        id: composer-cache
        run: 'echo "cache-files-dir=$(composer config cache-files-dir --global)" >> $GITHUB_OUTPUT'

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.cache-files-dir }}
            .github/phpcs/vendor
          key: ${{ runner.os }}-composer-phpcs-${{ hashFiles('.github/phpcs/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-phpcs-

      - name: Composer Install
        run: 'cd .github/phpcs && composer install --no-progress --classmap-authoritative'

      - name: Run PHP Coding Standards and Compatibility
        run: '.github/phpcs/vendor/bin/phpcs --standard=.github/phpcs/phpcs.xml'

  php-stan:
    name: 'PHP Stan. WordPress ${{ matrix.config.wordpress }}. bbPress ${{ matrix.config.bbpress }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # Lowest supported versions of WordPress and bbPress
          - wordpress: 4.1-branch
            bbpress: 2.5

          # Latest WordPress 5.*
          - wordpress: 5.9-branch
            bbpress: 2.5

          # WordPress 6.0.*
          - wordpress: 6.0-branch
            bbpress: 2.6

          # Latest versions of WordPress and bbPress
          - wordpress: 6.8-branch
            bbpress: 2.6
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          ini-file: development
          extensions: ''
          tools: composer

      - name: Detect Composer Cache Directory
        id: composer-cache
        run: 'echo "cache-files-dir=$(composer config cache-files-dir --global)" >> $GITHUB_OUTPUT'

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.cache-files-dir }}
            .github/php-stan/vendor
          key: ${{ runner.os }}-composer-php-stan-${{ hashFiles('.github/php-stan/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-php-stan-

      - name: Composer Install
        working-directory: .github/php-stan
        run: 'composer install --no-progress --classmap-authoritative'

      - name: Cache PHP Stan Stubs
        id: 'cache-php-stan-stubs'
        uses: actions/cache@v4
        with:
          path: |
            .github/php-stan/.cache
          key: php-stan-stubs-${{ matrix.config.wordpress }}--${{ matrix.config.bbpress }}
          restore-keys: |
            php-stan-stubs-

      - name: Checkout WordPress
        uses: actions/checkout@v4
        if: steps.cache-php-stan-stubs.outputs.cache-hit != 'true'
        with:
          repository: WordPress/WordPress
          ref: ${{ matrix.config.wordpress }}
          path: .github/php-stan/.cache/wordpress
          show-progress: false

      - name: Checkout bbPress
        uses: actions/checkout@v4
        if: steps.cache-php-stan-stubs.outputs.cache-hit != 'true'
        with:
          repository: bbpress/bbPress
          ref: ${{ matrix.config.bbpress }}
          path: .github/php-stan/.cache/bbpress
          show-progress: false

      - name: Generate PHP Stan Stubs. WordPress ${{ matrix.config.wordpress }}
        if: steps.cache-php-stan-stubs.outputs.cache-hit != 'true'
        working-directory: .github/php-stan
        run: 'vendor/bin/generate-stubs --no-interaction ./.cache/wordpress --out=./.cache/stubs/wordpress.stub'

      - name: Generate PHP Stan Stubs. bbPress ${{ matrix.config.bbpress }}
        if: steps.cache-php-stan-stubs.outputs.cache-hit != 'true'
        working-directory: .github/php-stan
        run: 'vendor/bin/generate-stubs --no-interaction ./.cache/bbpress --out=./.cache/stubs/bbpress.stub'

      - name: Run PHP Stan
        run: '.github/php-stan/vendor/bin/phpstan analyse --no-interaction --no-progress --configuration=.github/php-stan/php-stan.neon'
        continue-on-error: true # TODO: remove this parameter after fixing the code

  psalm-pre:
    name: Prepare Psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # Lowest supported versions of WordPress and bbPress
          - wordpress: 4.1-branch
            bbpress: 2.5

          # Latest WordPress 5.*
          - wordpress: 5.9-branch
            bbpress: 2.5

          # WordPress 6.0.*
          - wordpress: 6.0-branch
            bbpress: 2.6

          # Latest versions of WordPress and bbPress
          - wordpress: 6.8-branch
            bbpress: 2.6
    permissions:
      contents: read
    steps:
      - name: Hooks cache
        id: hooks-cache
        uses: actions/cache@v4
        with:
          path: |
            .github/hooks-generator/.cache/wordpress-hooks
            .github/hooks-generator/.cache/bbpress-hooks
          key: hooks-generator-hooks-wordpress-${{ matrix.config.wordpress }}-bbpress-${{ matrix.config.bbpress }}
          restore-keys: hooks-generator-hooks-

      - name: Checkout code
        uses: actions/checkout@v4
        if: steps.hooks-cache.outputs.cache-hit != 'true'

      - name: Run Hooks Generator
        uses: ./.github/actions/hooks-generator
        if: steps.hooks-cache.outputs.cache-hit != 'true'
        with:
          wordpress: ${{ matrix.config.wordpress }}
          bbpress: ${{ matrix.config.bbpress }}

  psalm:
    needs: psalm-pre
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # Lowest supported versions of WordPress and bbPress
          - wordpress: 4.1-branch
            bbpress: 2.5

          # Latest WordPress 5.*
          - wordpress: 5.9-branch
            bbpress: 2.5

          # WordPress 6.0.*
          - wordpress: 6.0-branch
            bbpress: 2.6

          # Latest versions of WordPress and bbPress
          - wordpress: 6.8-branch
            bbpress: 2.6
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          ini-file: development
          extensions: ''
          tools: composer

      - name: Detect Composer Cache Directory
        id: composer-cache
        shell: bash
        run: 'echo "cache-files-dir=$(composer config cache-files-dir --global)" >> $GITHUB_OUTPUT'

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.cache-files-dir }}
            .github/psalm/vendor
          key: ${{ runner.os }}-psalm-composer-${{ hashFiles('.github/psalm/composer.lock') }}
          restore-keys: ${{ runner.os }}-psalm-composer-

      - name: Composer Install
        working-directory: .github/psalm
        run: 'composer install --no-progress --classmap-authoritative'

      - name: Hooks Cache
        id: hooks-cache
        uses: actions/cache@v4
        with:
          path: |
            .github/hooks-generator/.cache/wordpress-hooks
            .github/hooks-generator/.cache/bbpress-hooks
          key: hooks-generator-hooks-wordpress-${{ matrix.config.wordpress }}-bbpress-${{ matrix.config.bbpress }}
          restore-keys: hooks-generator-hooks-
          fail-on-cache-miss: true

      - name: Dependencies cache
        id: dependencies-cache
        uses: actions/cache@v4
        with:
          path: |
            .github/hooks-generator/.cache/wordpress
            .github/hooks-generator/.cache/bbpress
          key: hooks-generator-dependencies-wordpress-${{ matrix.config.wordpress }}-bbpress-${{ matrix.config.bbpress }}
          restore-keys: hooks-generator-dependencies-

      - name: Checkout WordPress
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: WordPress/WordPress
          ref: ${{ matrix.config.wordpress }}
          path: .github/hooks-generator/.cache/wordpress
          show-progress: false

      - name: Checkout bbPress
        if: steps.dependencies-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: bbpress/bbPress
          ref: ${{ matrix.config.bbpress }}
          path: .github/hooks-generator/.cache/bbpress
          show-progress: false

      - name: Psalm Cache
        uses: actions/cache@v4
        with:
          path: .github/psalm/.cache/psalm
          key: psalm-cache-wordpress-${{ matrix.config.wordpress }}-bbpress-${{ matrix.config.bbpress }}
          restore-keys: psalm-cache-

      - name: Psalm
        run: .github/psalm/vendor/bin/psalm --config=".github/psalm/psalm.xml"
        continue-on-error: true
