name: Application Tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MYSQL_DATABASE:
        required: true
      MYSQL_USER:
        required: true
      MYSQL_PASSWORD:
        required: true
      MYSQL_ROOT_PASSWORD:
        required: true

      TEST_SITE_ADMIN_LOGIN:
        required: true
      TEST_SITE_ADMIN_PASSWORD:
        required: true
      TEST_SITE_ADMIN_EMAIL:
        required: true

    inputs:
      TEST_SITE_DOMAIN:
        type: string
        default: 'one.wordpress.test'
        required: true
      TEST_SITE_TITLE:
        type: string
        default: 'Test Site'
        required: true
      TEST_SITE_LOCALE:
        type: string
        default: 'en_US'
        required: true

jobs:
  application-tests:
    name: Application Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        cleanup: true

    - name: Docker Compose Build --help
      working-directory: .github/tests/application
      run: docker compose build --help

    - name: Docker Compose Up
      working-directory: .github/tests/application
      run: make up
      env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        TEST_SITE_ADMIN_LOGIN: ${{ secrets.TEST_SITE_ADMIN_LOGIN }}
        TEST_SITE_ADMIN_PASSWORD: ${{ secrets.TEST_SITE_ADMIN_PASSWORD }}
        TEST_SITE_ADMIN_EMAIL: ${{ secrets.TEST_SITE_ADMIN_EMAIL }}
        TEST_SITE_DOMAIN: ${{ inputs.TEST_SITE_DOMAIN }}
        TEST_SITE_TITLE: ${{ inputs.TEST_SITE_TITLE }}
        TEST_SITE_LOCALE: ${{ inputs.TEST_SITE_LOCALE }}

    - name: Composer Install
      working-directory: .github/tests/application
      run: make composer_install_from_host

    - name: Run Application Tests
      working-directory: .github/tests/application
      run: make run_tests_from_host

    - name: Docker Compose Down
      working-directory: .github/tests/application
      if: always()
      run: make down
