name: Code Testing

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'feature/**'
  workflow_dispatch:

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

jobs:
  debug:
    name: 'Debug environment variables'
    runs-on: ubuntu-latest
    steps:
      - name: Debug GITHUB_ Variables
        run: env | grep GITHUB_

      - name: Dump github Variable
        run: echo '${{ toJson(github) }}'
