name: Code Testing

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'feature/**'

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

permissions: {}

jobs:
  php-syntax-check:
    name: 'PHP ${{ matrix.php-versions }} Syntax Check'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: none
          tools: none
          ini-file: development
          php-version: ${{ matrix.php-versions }}

      - name: Run PHP Syntax Check
        run: 'find . -type f -name "*.php" -print0 | xargs --null --verbose --max-procs=4 --max-args=1 php --syntax-check'

  phpcs:
    name: 'PHP Coding Standards and Compatibility'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          ini-file: development
          extensions: filter, libxml, tokenizer, xmlreader, iconv, mbstring
          tools: composer

      - name: Detect Composer Cache Directory
        id: composer-cache
        run: 'echo "cache-files-dir=$(composer config cache-files-dir --global)" >> $GITHUB_OUTPUT'

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.cache-files-dir }}
            .github/phpcs/vendor
          key: ${{ runner.os }}-composer-phpcs-${{ hashFiles('.github/phpcs/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-phpcs-

      - name: Composer Install
        run: 'cd .github/phpcs && composer install --no-progress --classmap-authoritative'

      - name: Run PHP Coding Standards and Compatibility
        run: '.github/phpcs/vendor/bin/phpcs --standard=.github/phpcs/phpcs.xml'

  php-stan:
    name: 'PHP Stan. WordPress ${{ matrix.config.wordpress }}. bbPress ${{ matrix.config.bbpress }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - wordpress: 4.1-branch
            bbpress: 2.5
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          ini-file: development
          extensions: ''
          tools: composer

      - name: Detect Composer Cache Directory
        id: composer-cache
        run: 'echo "cache-files-dir=$(composer config cache-files-dir --global)" >> $GITHUB_OUTPUT'

      - name: Composer Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.cache-files-dir }}
            .github/php-stan/vendor
          key: ${{ runner.os }}-composer-php-stan-${{ hashFiles('.github/php-stan/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-php-stan-

      - name: Composer Install
        working-directory: .github/php-stan
        run: 'composer install --no-progress --classmap-authoritative'

      - name: WordPress and bbPress Cache
        id: 'cache-wordpress-bbpress'
        uses: actions/cache@v4
        with:
          path: |
            .github/php-stan/.cache
          key: ${{ runner.os }}-php-stan--wordpress-bbpress--${{ matrix.config.wordpress }}--${{ matrix.config.bbpress }}
          restore-keys: |
            ${{ runner.os }}-php-stan--wordpress-bbpress--

      - name: Checkout WordPress
        uses: actions/checkout@v4
        if: steps.cache-wordpress-bbpress.outputs.cache-hit != 'true'
        with:
          repository: WordPress/WordPress
          ref: ${{ matrix.config.wordpress }}
          path: .github/php-stan/.cache/wordpress
          show-progress: false

      - name: Checkout bbPress
        uses: actions/checkout@v4
        if: steps.cache-wordpress-bbpress.outputs.cache-hit != 'true'
        with:
          repository: bbpress/bbPress
          ref: ${{ matrix.config.bbpress }}
          path: .github/php-stan/.cache/bbpress
          show-progress: false

      - name: Generate Stubs. WordPress ${{ matrix.config.wordpress }}
        if: steps.cache-wordpress-bbpress.outputs.cache-hit != 'true'
        working-directory: .github/php-stan
        run: 'vendor/bin/generate-stubs --no-interaction ./.cache/wordpress --out=./.cache/stubs/wordpress.stub'

      - name: Generate Stubs. bbPress ${{ matrix.config.bbpress }}
        if: steps.cache-wordpress-bbpress.outputs.cache-hit != 'true'
        working-directory: .github/php-stan
        run: 'vendor/bin/generate-stubs --no-interaction ./.cache/bbpress --out=./.cache/stubs/bbpress.stub'

      - name: Run PHP Stan
        run: '.github/php-stan/vendor/bin/phpstan analyse --no-interaction --no-progress --configuration=.github/php-stan/php-stan.neon'
