name: Trivy

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      WORDPRESS_ARG_BASE_IMAGE:
        type: string
        default: 'wordpress:latest'
        required: true
      WORDPRESS_ARG_PLUGIN_BBPRESS_ZIP_URL:
        type: string
        default: 'https://downloads.wordpress.org/plugin/bbpress.2.6.0.zip'
        required: true
      WORDPRESS_ARG_THEME_ZIP_URL:
        type: string
        default: 'https://downloads.wordpress.org/theme/twentytwelve.4.7.zip'
        required: true
#      WORDPRESS_DOMAIN:
#        type: string
#        default: 'one.wordpress.test'
#        required: false
#      WORDPRESS_SITE_TITLE:
#        type: string
#        default: 'Test Site'
#        required: false
#      WORDPRESS_SITE_LOCALE:
#        type: string
#        default: 'en_US'
#        required: false
      CLI_ARG_BASE_IMAGE:
        type: string
        default: 'wordpress:cli'
        required: true

concurrency:
  group: trivy
  cancel-in-progress: true

permissions: {}

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          cleanup: true

      - name: Docker Bake
        uses: docker/bake-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          files: docker-compose.yml
          source: ./tests/application
          targets: php,php-develop,syslog,wordpress
          set: |
            wordpress.args.WORDPRESS_ARG_BASE_IMAGE=${{ inputs.WORDPRESS_ARG_BASE_IMAGE }}
            wordpress.args.WORDPRESS_ARG_PLUGIN_BBPRESS_ZIP_URL=${{ inputs.WORDPRESS_ARG_PLUGIN_BBPRESS_ZIP_URL }}
            wordpress.args.WORDPRESS_ARG_THEME_ZIP_URL=${{ inputs.WORDPRESS_ARG_THEME_ZIP_URL }}
            wordpress.args.CLI_ARG_BASE_IMAGE=${{ inputs.CLI_ARG_BASE_IMAGE }}

      - name: Run Trivy. Application Tests [syslog]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: syslog:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-syslog.sarif

      - name: Run Trivy. Application Tests [php]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: php:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-php.sarif

      - name: Run Trivy. Application Tests [php-develop]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: php-develop:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-php-develop.sarif

      - name: Run Trivy. Application Tests [wordpress]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: wordpress:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-wordpress.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ runner.temp }}/trivy
