name: Trivy

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

concurrency:
  group: trivy
  cancel-in-progress: true

permissions: {}

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          cleanup: true

      - name: Docker Bake
        uses: docker/bake-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          files: docker-compose.yml
          source: ./tests/application
          targets: php,php-develop,syslog,wordpress
          load: true
          set: |
            wordpress.args.WORDPRESS_ARG_BASE_IMAGE=wordpress:latest
            wordpress.args.WORDPRESS_ARG_PLUGIN_BBPRESS_ZIP_URL=https://downloads.wordpress.org/plugin/bbpress.2.6.0.zip
            wordpress.args.WORDPRESS_ARG_THEME_ZIP_URL=https://downloads.wordpress.org/theme/twentytwelve.4.7.zip
            wordpress.args.CLI_ARG_BASE_IMAGE=wordpress:cli

      - name: Docker. List images
        working-directory: ./tests/application
        run: docker images

      - name: Create folder for Trivy files
        working-directory: ${{ runner.temp }}
        run: mkdir trivy

      - name: Run Trivy. Application Tests [syslog]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: bbpress-permalinks-with-id-application-tests-syslog:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-syslog.sarif

      - name: Run Trivy. Application Tests [php]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: bbpress-permalinks-with-id-application-tests-php:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-php.sarif
          skip-setup-trivy: true

      - name: Run Trivy. Application Tests [php-develop]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: bbpress-permalinks-with-id-application-tests-php-develop:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-php-develop.sarif
          skip-setup-trivy: true

      - name: Run Trivy. Application Tests [wordpress]
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: bbpress-permalinks-with-id-application-tests-wordpress:latest
          format: sarif
          output: ${{ runner.temp }}/trivy/trivy-results--tests-application-wordpress.sarif
          skip-setup-trivy: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ runner.temp }}/trivy
